POST https://impressive-cathee-immune-angelceb-312ac472.koyeb.app/api/users/register
Content-Type: application/json

{
  "name": "jajajja",
  "birthdate": "1999-01-13",
  "email": "angelbaysexyyeahah@ahah.com",
  "password": "securePass123",
  "confirmPassword": "securePass123"
}


###
POST https://impressive-cathee-immune-angelceb-312ac472.koyeb.app/api/users/login
Content-Type: application/json

{
  "email": "angel@xoxo.com",
  "password": "27486201"
}

###
PATCH http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGE3MDU5MjM0NGM2NzE0OWNhYThlMDMiLCJuYW1lIjoiQWxpY2UgRXhhbXBsZSIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJiaXJ0aGRhdGUiOiIxOTk1LTA1LTIwVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3NTU3ODk1ODMsImV4cCI6MTc4NzMyNTU4M30.AmppTKLapNPzb0VylsZ-tSTfZO5ck4G_pjnGM3BzekY

{
  "name": "Alice Examplexxxx",
  "birthdate": "1995-05-20",
  "email": "alice@example.com",
  "password": "securePass123"
}

###
DELETE http://localhost:3000/api/users/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGE3MDU5MjM0NGM2NzE0OWNhYThlMDMiLCJuYW1lIjoiQWxpY2UgRXhhbXBsZSIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJiaXJ0aGRhdGUiOiIxOTk1LTA1LTIwVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3NTU3ODk1ODMsImV4cCI6MTc4NzMyNTU4M30.AmppTKLapNPzb0VylsZ-tSTfZO5ck4G_pjnGM3BzekY

###
GET http://localhost:3000/api/users/google

###
# Get user test results (OCEAN test)
# Replace USER_ID with an actual user ID from your database
GET http://localhost:3000/api/ocean/user/68b41d35238816729c62281f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGI0MWQzNTIzODgxNjcyOWM2MjI4MWYiLCJuYW1lIjoiQW5nZWwiLCJlbWFpbCI6ImFuZ2VsQHhveG8uY29tIiwiYmlydGhkYXRlIjoiMTk5OS0xMi0yN1QwMDowMDowMC4wMDBaIiwiaWF0IjoxNzY5MDI4OTM4LCJleHAiOjE4MDA1NjQ5Mzh9.dT4t_nNtNM7B0omZFx86SO8eT72Qe-QVrFxHzqgFjWc

###
# Get user test results (Production)
# Replace USER_ID with an actual user ID from your database
GET https://impressive-cathee-immune-angelceb-312ac472.koyeb.app/api/ocean/user/68a70592344c67149caa8e03
Authorization: Bearer YOUR_TOKEN_HERE